# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98e83316ad0b668156e907a8daf9ac83001a043f33e07fb4ddaf46f4197f1c6cfb5a3c461b8bf39a76414c03494d9c2efbb37c25444f1a7518cacebf142f92f9

test:
  secret_key_base: 055813be21f521c10c13d33c006fa034bc83b4b7eafdee8d31567ee98c51d5c73bbd29d2604af75d7d13cd4b406bdcc3544b40c4e6d3df75d3f8b3fc4b69c52a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
